First implementation of responsive-layout blocks
vtex-apps/responsive-layout pull request #1
Opened 2019-10-10 18:30 UTC by victorhmp

#### What does this PR do?

Creates four new blocks:

- `responsive-layout.desktop`
- `responsive-layout.mobile`
- `responsive-layout.tablet`
- `responsive-layout.phone`

Each of those blocks has composition `children`, and will only render their children in the correct screen-sizes.

#### How to test it? \*

Just resize the window and see the magic take place:
https://victorhmp--storecomponents.myvtex.com/about-us

2019-10-10 18:42 UTC, victorhmp commented
@lbebber this is the most straightforward implementation possible, but it might not be the smartest hahahah I don't know if we need something more refined than that

2019-10-10 18:47 UTC, klzns requested changes

2019-10-10 18:47 UTC, klzns commented on react/ResponsiveLayoutDummy.tsx
> +  return <span />
Return null

2019-10-10 18:47 UTC, klzns commented on react/ResponsiveLayoutDummy.tsx
> +  console.warn(
Console.error

2019-10-10 18:57 UTC, klzns submitted a review, later dismissed

2019-10-11 13:58 UTC, klzns commented on docs/README.md
> +```json
I think this part of our docs is useless.

I would jump right into some examples of usage.

2019-10-15 17:14 UTC, iaronaraujo approved these changes

2019-10-15 17:18 UTC, merged