Creation of crowdin file
vtex-apps/responsive-layout pull request #13
Opened 2021-07-06 20:24 UTC by daniserejo

#### What problem is this solving?

Creation of crowdin file

2021-07-06 21:32 UTC, camilavcoutinho requested changes
Something is strange with Changelog.

2021-07-07 21:08 UTC, camilavcoutinho approved these changes, later dismissed

2021-07-13 20:17 UTC, igorbrasileiro approved these changes, later dismissed
Remove changelog

2021-07-13 20:17 UTC, igorbrasileiro commented on CHANGELOG.md
> +
Not necessary, this PR is just for tooling.
```suggestion
```

2021-07-15 18:41 UTC, igorbrasileiro requested changes

2021-07-15 18:41 UTC, igorbrasileiro commented on .vscode/settings.json
> +  }
These changes are intended to? Maybe it's just an editor setting. Remove it

2021-07-15 18:41 UTC, igorbrasileiro commented on CHANGELOG.md
> +
Remove these changes.

2021-07-15 19:08 UTC, igorbrasileiro approved these changes

2021-07-15 19:09 UTC, merged