Explain that mobile contains tablet and phone
vtex-apps/responsive-layout pull request #2
Opened 2019-11-22 19:23 UTC by klzns

2019-11-22 19:51 UTC, guerreirobeatriz submitted a review, later dismissed

2020-06-09 16:34 UTC, victorhmp submitted a review, later dismissed

2020-06-09 16:46 UTC, Klynger submitted a review, later dismissed

2020-06-09 17:11 UTC, iaronaraujo requested changes

2020-06-09 17:11 UTC, iaronaraujo commented on CHANGELOG.md
> +
```suggestion
```

2020-06-09 17:11 UTC, iaronaraujo commented on CHANGELOG.md
> +
```suggestion
```

2020-06-10 01:47 UTC, guerreirobeatriz approved these changes

2020-06-10 16:37 UTC, Klynger approved these changes

2021-10-22 19:44 UTC, closed without merging